baseURL = "https://nathanjaremko.com/podcast/"
languageCode = "en-us"
title = "podcast"
theme = "minimal"

[params]
    author = "Nathan Jaremko"
    description = "podcast is command line podcast player"
    githubUsername = "njaremko"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Quicksand" # should match the name on Google Fonts!

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/download"
    name = "Install"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://github.com/njaremko/podcast"
    name = "github"
    weight = 1
